---
# tasks file for ansible-role-php
- name: Install software-properties-common
  apt: name=software-properties-common state=installed

# Add ppa for installing PHP 7
- name: Add the ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php' 

- name: Update the apt cache
  apt: update_cache=yes cache_valid_time=3600

# Install PHP and remove apache
- name: Install PHP
  apt: name={{item}} state=present
  with_items:
  - php
  - php-fpm
  - php-mysql
  - php-xml

- name: Remove apache
  apt: name=apache2 state=absent